### ISSUE TITLE
Problem when building

### ISSUE THREAD

**Issue by Eimji** [devsisters/goquic#16]
Hello,

I already tested your code a few months ago. I created a small code to build a "goquic" server. It worked without any issue.
Now, I come back to your code, and I get errors with go get github.com/devsisters/goquic
Here are errors:
/usr/bin/ld: ne peut trouver -lgoquic
/usr/bin/ld: ne peut trouver -lquic
/usr/bin/ld: ne peut trouver -lssl
/usr/bin/ld: ne peut trouver -lcrypto
/usr/bin/ld: ne peut trouver -lgoquic
/usr/bin/ld: ne peut trouver -lquic
/usr/bin/ld: ne peut trouver -lssl
/usr/bin/ld: ne peut trouver -lcrypto
/usr/bin/ld: ne peut trouver -lprotobuf
collect2: error: ld returned 1 exit status
(I am French, so errors are in French, so "ne peut trouver" means "does not find")

With my code and also with your example server.go in the folder examples, I get now these errors when compiling with: CGO_LDFLAGS="-L$GOPATH/src/github.com/devsisters/goquic/lib/linux_amd64" go build server.go

/tmp/go-build307624852/github.com/devsisters/goquic/_obj/dispatcher.cgo2.o: dans la fonction « _cgo_b3b031ad1652_Cfunc_quic_server_session_connection_stat »:
../github.com/devsisters/goquic/dispatcher.go:89: référence indéfinie vers « quic_server_session_connection_stat »
/tmp/go-build307624852/github.com/devsisters/goquic/_obj/quicstream_server.cgo2.o: dans la fonction « _cgo_b3b031ad1652_Cfunc_quic_simple_server_stream_write_headers »:
../github.com/devsisters/goquic/quicstream_server.go:37: référence indéfinie vers « quic_simple_server_stream_write_headers »
/tmp/go-build307624852/github.com/devsisters/goquic/_obj/quicstream_server.cgo2.o: dans la fonction « _cgo_b3b031ad1652_Cfunc_quic_simple_server_stream_write_or_buffer_data »:
../github.com/devsisters/goquic/quicstream_server.go:50: référence indéfinie vers « quic_simple_server_stream_write_or_buffer_data »
../github.com/devsisters/goquic/lib/linux_amd64/libgoquic.a(go_quic_spdy_client_stream.o): dans la fonction « net::tools::GoQuicSpdyClientStream::OnStreamHeadersComplete(bool, unsigned long) »:
/home/hodduc/go/src/github.com/devsisters/goquic/src/go_quic_spdy_client_stream.cc:44: référence indéfinie vers « GoQuicSpdyClientStreamOnStreamHeadersComplete_C »
../github.com/devsisters/goquic/lib/linux_amd64/libgoquic.a(go_quic_spdy_server_stream.o): dans la fonction « net::tools::GoQuicSpdyServerStream::OnStreamHeadersComplete(bool, unsigned long) »:
/home/hodduc/go/src/github.com/devsisters/goquic/src/go_quic_spdy_server_stream.cc:27: référence indéfinie vers « GoQuicSpdyServerStreamOnStreamHeadersComplete_C »
../github.com/devsisters/goquic/lib/linux_amd64/libgoquic.a(go_quic_spdy_server_stream.o): dans la fonction « net::tools::GoQuicSpdyServerStream::OnDataAvailable() »:
/home/hodduc/go/src/github.com/devsisters/goquic/src/go_quic_spdy_server_stream.cc:57: référence indéfinie vers « GoQuicSpdyServerStreamOnDataAvailable_C »
../github.com/devsisters/goquic/lib/linux_amd64/libgoquic.a(go_quic_spdy_server_stream.o): dans la fonction « net::tools::GoQuicSpdyServerStream::OnClose() »:
/home/hodduc/go/src/github.com/devsisters/goquic/src/go_quic_spdy_server_stream.cc:68: référence indéfinie vers « GoQuicSpdyServerStreamOnClose_C »
collect2: error: ld returned 1 exit status

Please, could you help me to find out how to use goquic ?

Thanks a lot in advance

**Comment by hodduc** [comment]
This is because that static libs on `$GOPATH/src/github.com/devsisters/goquic/lib` are not updated yet. You can run `./build_libs.sh` on `$GOPATH/src/github.com/devsisters/goquic` to force build static libs.

Anyway, I will update static libs on master soon.

**Comment by Eimji** [comment]
Thanks for your help, it works now :)
Do you plan to release a version for support of read streaming ? 

Best regards.

**Comment by gripedthumbtacks** [comment]
@Eimji The devs put a notice up that they would like to support it in the future, but there is no expected arrival date yet known.
