### ISSUE TITLE
goquic does not work with chromium 49 ?

### ISSUE THREAD

**Issue by Eimji** [devsisters/goquic#23]
Hello

I have just found that goquic (the server.go in the folder example, as well as my goquic-baser server implementation) did not work with the latest version of chromium 49.0.2623.87 (Built on 8.3, running on Debian 8.3 (64-bit)).When trying on another computer with chromium version 48, the server codes work flawlessly. 

Please, could you tell me if the problem is on my own side or not ?

Thanks in advance.

.

**Comment by hodduc** [comment]
Chromium team currently disabled QUIC on recent Chrome to connect non-Google hosts.
See this: https://groups.google.com/a/chromium.org/forum/#!topic/proto-quic/-KUJWxSjxnQ

To connect with GoQuic server, you should provide --quic-host-whitelist="<your domain>" flags on Chrome startup .

**Comment by Eimji** [comment]
Thanks a lot, you rock !!!
