### ISSUE TITLE
Connecting to quic reverse proxy always requires 3-RTT

### ISSUE THREAD

**Issue by cffan** [devsisters/goquic#31]
While trying out the quic reverse proxy, I found that the server always replies the my first CHLO with:

 RREJ: SERVER_NONCE_REQUIRED_FAILURE

Then the client will send another two requests, making the entire connection establishment 3-RTT.

**Comment by hodduc** [comment]
Which revision of GoQuic are you using? We added 0-RTT connection support from https://github.com/devsisters/goquic/commit/492debe4b7e17bf07fa77950b43562a38bb18b3b (turned off replay protection) and well working with the tip of master & most recent chrome browser.

**Comment by cffan** [comment]
After updating to the latest code, 0-RTT connection is working. Thanks!
