### ISSUE TITLE
build goquic failed

### ISSUE THREAD

**Issue by azurehongqiang** [devsisters/goquic#5]
libquic/src/base/memory/weak_ptr.h:289:34: error: ‘base::WeakPtrFactory<T>::WeakPtrFactory() [with T = net::GoQuicTimeWaitListManager]’ is private

gcc version 4.8.2 (GCC) 
Linux version 2.6.32-279

**Comment by serialx** [comment]
Please wait until #4 is merged.

**Comment by serialx** [comment]
The build will work again. Thanks for reporting!
